name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        
    - name: Install dependencies
      run: npm install
      
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Get current version
      id: package_version
      run: echo "::set-output name=current_version::$(node -p "require('./package.json').version")"
      
    - name: Increment version
      id: increment_version
      run: |
        npm version ${{ github.event.inputs.release_type }} --no-git-tag-version
        echo "::set-output name=new_version::$(node -p "require('./package.json').version")"
        
    - name: Commit and push version change
      run: |
        git add package.json
        git commit -m "Bump version to ${{ steps.increment_version.outputs.new_version }}"
        git push
        git tag v${{ steps.increment_version.outputs.new_version }}
        git push --tags
        
    - name: Package application
      run: npm run package
      
    - name: Zip Windows application
      run: |
        cd dist
        powershell Compress-Archive -Path recipe-calculator-win32-x64 -DestinationPath recipe-calculator-win32-x64.zip
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.increment_version.outputs.new_version }}
        name: Release v${{ steps.increment_version.outputs.new_version }}
        files: |
          dist/recipe-calculator-win32-x64.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
